apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark-log-reader-serviceaccount
  namespace: benchmark-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: benchmark-log-reader-role
  namespace: benchmark-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: benchmark-log-reader-rolebinding
  namespace: benchmark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: benchmark-log-reader-role
subjects:
- kind: ServiceAccount
  name: benchmark-log-reader-serviceaccount
  namespace: benchmark-operator
